sudo: false

language: node_js

node_js:
  - 10
  - 8

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn
  - npm i -g codecov

script:
  - yarn prepublishOnly && codecov --disable=gcov
