trigger:
  branches:
    include:
    - master
    - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Resolve Dependencies'

- script: |
    npm run build
  displayName: 'Build Solution'

- task: npmAuthenticate@0
  inputs:
    customEndpoint: 'NPM connection 1'
    workingFile: .npmrc

- script: |
    sed -i -e "s/\(\"version\":\\s\+\"\([0-9]\+\.\?\)\+\)/\1-pre.$BUILD_BUILDNUMBER/" package.json;
    npm publish --tag next
  displayName: 'Pre-Release if develop'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))

- script: |
    npm publish
  displayName: 'Release if master'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
